### ISSUE TITLE
spf_dmarc eval in macro spf_dkim_dmarc_checks not working as expected

### ISSUE THREAD

**Issue by jbouwh** [aholzel/SA-dmarc#8]
See pull request to fix this:
https://github.com/aholzel/SA-dmarc/pull/7

The eval for spf_dmarc uses spf_domain which is not set. Changed this with spf_domain_1.
This issue had impact on mail subdomains.

**Comment by aholzel** [comment]
@jbouwh sorry for the late response. I created a new version that also addresses these problems. Thank you very much!
